# 自动求梯度gradient
深度学习中我们经常要对函数自动求梯度，Pytorch提供的**autograd**包能根据输入和前向传播过程自动构建计算图，并执行反向传播，本节将介绍autograd包相关操作

In [2]:
import torch

In [4]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
print(x.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [8]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [13]:
z = y * y * 3
out = z.mean()
print(out.grad_fn)
print(out.backward())
print(x.grad)

None
tensor([[9., 9.],
        [9., 9.]])
