In [2]:
import numpy as np
import torch

In [3]:
#  创建未初始化的shape为5*3的Tensor
x = torch.empty(5, 3)
print(x)

tensor([[6.8878e-39, 1.0653e-38, 1.0102e-38],
        [8.4490e-39, 9.6428e-39, 1.1112e-38],
        [9.5511e-39, 1.0102e-38, 1.0286e-38],
        [1.0194e-38, 9.6429e-39, 9.2755e-39],
        [9.1837e-39, 9.3674e-39, 1.0745e-38]])


In [4]:
# 创建随机初始化的shape为5*3的Tensor
x = torch.rand(5, 3) # rand 范围为[0, 1]
print(x)

tensor([[0.0341, 0.2135, 0.5196],
        [0.9246, 0.2513, 0.3087],
        [0.7444, 0.2932, 0.1207],
        [0.3425, 0.7281, 0.8300],
        [0.7456, 0.8314, 0.2793]])


In [5]:
# 创建一个全0的Tensor
z = torch.zeros(5, 3, dtype=torch.long)
print(z)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
# 根据数据直接创建Tensor
x = torch.tensor([5.5, 3], dtype=torch.float)
print(x)

tensor([5.5000, 3.0000])


In [7]:
print(x.size())
print(x.shape)

torch.Size([2])
torch.Size([2])


In [8]:
y = z[:, 1]
y += 1
print(y) # 源Tensor也会跟着改变，所以数字越来越大

tensor([1, 1, 1, 1, 1])


In [9]:
y = z.view(15)
print(y)
y = z.view(-1, 5) # -1指的是这个维度可以根据其他维度推出来
print(y)

tensor([0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0])
tensor([[0, 1, 0, 0, 1],
        [0, 0, 1, 0, 0],
        [1, 0, 0, 1, 0]])


当我们想要一个新的副本（不共享内存相互独立），我们可以用reshape()函数改变形状，但我们用此函数不能保证返回的是其拷贝的tensor,所以我们更推荐先clone一个副本再使用view

In [10]:
y_cp = y.clone().view(15)
y += 1
print(y)
print(y_cp)


tensor([[1, 2, 1, 1, 2],
        [1, 1, 2, 1, 1],
        [2, 1, 1, 2, 1]])
tensor([0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0])


# 广播机制
当我们用两个不同shape的tensor做运算，可能会触发广播机制，即先适当复制两个tensor使其形状相同再进行运算

In [11]:
x = torch.arange(1, 3).view(1, 2)
y = torch.arange(1, 4).view(3, 1)

print(x)
print(y)

print(x+y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [12]:
# tensor 和 numpy之间的互换
a = torch.ones(4)
b = a.numpy()
print(a)
print(b)
a += 1
print(a)
print(b)
b += 1
print(a)
print(b)

tensor([1., 1., 1., 1.])
[1. 1. 1. 1.]
tensor([2., 2., 2., 2.])
[2. 2. 2. 2.]
tensor([3., 3., 3., 3.])
[3. 3. 3. 3.]


In [13]:
a = np.ones(4)
b = torch.from_numpy(a)
print(a, b)

[1. 1. 1. 1.] tensor([1., 1., 1., 1.], dtype=torch.float64)


In [18]:
x = torch.tensor([2, 1])
y = torch.tensor([2, 2])
z = torch.matmul(x, y)
print(z)

tensor(6)
